services:
  db:
    image: 'postgres:latest'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: my-postgres-db-pwd
  identity:
    image: 'quay.io/keycloak/keycloak:latest'
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --import-realm
    ports:
      - '8180:8080'
    environment:
      KEYCLOAK_LOGLEVEL: 'INFO'
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin-secret'
      KC_HOSTNAME: 'localhost'
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'